import Head from 'next/head'
import Content from '../components/Content'
import MainSearch from '../components/Mainsearch'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Mallu Nighandu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSearch/>
      <Content/>
    </div>
  )
}
