import Register from "../components/Register";
import Head from "next/head";

const RegisterPage = () => {
  return (
    <>
      <Head>
        <title>Mallu Nighandu - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Register />
    </>
  );
};

export default RegisterPage;